# Train Notebook

In [3]:
import pandas as pd

In [4]:
CURRENCY_TO_TRAIN = "CARD"
PROCESSED_DATA_PATH = '../processed-data/'
MODELS_OUTPUT_PATH = './models/'

In [5]:
currency = "CARD"
data_path = f'{PROCESSED_DATA_PATH}{currency}_master_dataset.parquet'
master_df = pd.read_parquet(data_path)

In [17]:
master_df.shape

(44649, 97)

In [24]:
# get the last row-label in master_df where the column 'index' equals 399
last_idx = master_df[master_df['index'] == 399].last_valid_index()
print(last_idx)

39639

In [ ]:
# get all rows of master_df at and below row index 39636
master_df_tail = master_df.iloc[last_idx-3:]
master_df_tail

,index,forecast_horizon,target,open,close,high,low,mid,body,range,...,close_div_ema_100,close_div_ema_200,close_div_ema_400,range_std_12,range_std_25,range_std_50,macd,macd_signal,macd_hist,time
count,5013.000000,5013.000000,5013.000000,5013.000000,5013.000000,5013.000000,5013.000000,5013.000000,5013.000000,5013.000000,...,5013.000000,5013.000000,5013.000000,5013.000000,5013.000000,5013.000000,5013.000000,5013.000000,5013.000000,5.013000e+03
mean,1096.328346,30.018153,100060.597048,100005.051466,100002.557750,100180.443447,99857.984041,100020.348693,-2.493716,322.459406,...,1.000321,1.000176,1.000109,157.865025,160.623719,161.330488,12.388782,11.472977,0.915805,1.097400e+06
std,408.496449,17.377730,1198.134131,1293.235835,1288.643388,1294.875817,1289.233336,1290.325601,102.841948,164.253605,...,0.011239,0.012018,0.012482,44.055238,30.497316,23.371874,324.554220,284.863281,137.690828,4.084963e+05
min,399.000000,1.000000,96833.000000,96443.000000,96451.000000,96721.000000,96315.000000,96449.000000,-358.000000,28.000000,...,0.964882,0.963720,0.964674,42.717802,86.909110,108.799994,-873.252379,-686.339673,-459.770725,4.000700e+05
25%,758.000000,15.000000,99242.000000,99158.000000,99176.000000,99309.000000,99027.000000,99228.000000,-73.000000,202.000000,...,0.992648,0.991894,0.991957,124.895229,142.480092,146.817567,-205.042560,-180.393732,-99.139464,7.590700e+05
50%,1117.000000,30.000000,100054.000000,100022.000000,100017.000000,100207.000000,99905.000000,100000.000000,-13.000000,297.000000,...,1.000640,1.000429,1.000325,156.946116,158.125920,158.925423,13.268351,14.205685,1.373879,1.118071e+06
75%,1464.000000,45.000000,100785.000000,100838.000000,100829.000000,101041.000000,100684.000000,100907.000000,71.000000,408.000000,...,1.007707,1.007703,1.007719,183.283747,175.513029,175.477105,217.962977,177.846151,104.971503,1.465070e+06
max,1799.000000,60.000000,102881.000000,103818.000000,103797.000000,103926.000000,103627.000000,103814.000000,370.000000,1205.000000,...,1.037295,1.040528,1.041020,336.065289,280.094109,242.297864,1010.145034,797.559635,391.661279,1.800080e+06

In [30]:
print(master_df.describe())

              index  forecast_horizon         target           open  \
count  44649.000000      44649.000000   44649.000000   44649.000000
mean    1069.380703         29.666868  100121.325472  100086.867500
std      393.663200         17.436076    1352.521539    1332.500885
min      399.000000          1.000000   96061.000000   95280.000000
25%      724.000000         14.000000   99219.000000   99207.000000
50%     1055.000000         29.000000  100054.000000  100044.000000
75%     1401.000000         45.000000  101042.000000  100926.000000
max     1799.000000         60.000000  104734.000000  105216.000000

               close           high            low            mid  \
count   44649.000000   44649.000000   44649.000000   44649.000000
mean   100086.542767  100261.525118   99945.459742  100103.909830
std      1329.502689    1335.229888    1330.820824    1330.247611
min     95390.000000   95560.000000   95005.000000   95335.000000
25%     99211.000000   99370.000000   99056.000000   99228.000000
50%    100046.000000  100235.000000   99927.000000  100129.000000
75%    100925.000000  101107.000000  100782.000000  100907.000000
max    105321.000000  105442.000000  105214.000000  105299.000000

               body         range  ...  close_div_ema_100  close_div_ema_200  \
count  44649.000000  44649.000000  ...       44649.000000       44649.000000
mean      -0.324733    316.065377  ...           1.000204           1.000202
std      102.060039    161.051314  ...           0.011994           0.012663
min     -368.000000     28.000000  ...           0.958569           0.957523
25%      -67.000000    198.000000  ...           0.992081           0.991644
50%       -9.000000    290.000000  ...           1.000004           0.999989
75%       69.000000    404.000000  ...           1.008202           1.008502
max      371.000000   1411.000000  ...           1.040992           1.044692

       close_div_ema_400  range_std_12  range_std_25  range_std_50  \
count       44649.000000  44649.000000  44649.000000  44649.000000
mean            1.000186    155.535537    158.752937    160.055433
std             0.013010     43.289572     28.436941     19.750262
min             0.955330     41.989447     86.909110    108.799994
25%             0.991478    123.802874    140.776418    147.463214
50%             0.999941    151.709326    157.253543    159.153757
75%             1.008551    180.292103    173.904159    171.927127
max             1.048108    341.730212    280.094109    242.297864

               macd   macd_signal     macd_hist          time
count  44649.000000  44649.000000  44649.000000  4.464900e+04
mean       6.577177      5.426490      1.150687  1.070427e+06
std      361.674880    319.982340    151.867818  3.936634e+05
min    -1341.335744  -1125.203631   -526.552052  4.000250e+05
25%     -236.732042   -208.688425   -103.990644  7.250250e+05
50%        9.626334      9.970550      0.334925  1.056025e+06
75%      249.451730    219.386682    106.424200  1.402019e+06
max     1448.178467   1293.536233    742.746784  1.800112e+06

[8 rows x 96 columns]